### ISSUE TITLE
Order - sale - distribution with no recipe didn't work 

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#306]
We ran this sequence for a resource type without a recipe, so no plan was created.  Tried to then do it without a plan (Plan Work), selecting the correct order.  Then added in the commitment on the process page to try to hook it up.  It basically didn't hold together, the order didn't know it's process.

I don't know if this would have worked if we had selected the output resource on the Plan Work page so commitments would have been created immediately.  If so, maybe this is the only solution needed?

After this the All Work page was blowing up also, trying to display the process we created.  (Deleted the process in valdev to fix this, so the data is no longer intact there.)

**Comment by bhaugen** [comment]
Plan Work now works correctly if you specify a process output. But if you don't, and then add output requirements on the process, the process has no way to be connected to the order.

**Comment by bhaugen** [comment]
Added a button to the order schedule page to create a production process for order items that need one. Much easier than using Plan Work.
