### ISSUE TITLE
Cash receipt not showing up on distribution page

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#307]
Create a sale, with a cash receipt.  The cash receipt did not show up on the distribution.

I suspect this has to do with that we created the order for an exchange firm (BDan), while otherwise we were using the project (Course 3D).

Need to re-create and investigate.

**Comment by bhaugen** [comment]
fixed in https://github.com/valnet/valuenetwork/commit/f04e0d8d38d287bebc5e21bfbbdd186dd4435854
