### ISSUE TITLE
All Work page blows up after process creation

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#310]
Sequence:
1. created customer order for item without recipe
2. Plan Work, created process and chose this order
3. On process logging page, logged work (All Work still worked)
4. logged output commitment (All Work still worked, pretty sure)
5. logged output event (All Work blows up)

(This is connected to the bugs logged Monday after working with Tibi.)

**Comment by bhaugen** [comment]
closed by https://github.com/valnet/valuenetwork/commit/383301c4b2c76cf914fe4b77818be599cad11b66
