### ISSUE TITLE
Get rid of constraint of needing output in pattern before creating recipe

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#313]
You don't get buttons to create recipe until the resource type has been included in the output of some pattern.  This seems excessive.  It is possible this is needed, but we can't really say so right now.  In any case, it is confusing.

We could try removing the constraint and then see if we run into problems making the recipe.

Good candidate for a troubleshooting framework.

**Comment by bhaugen** [comment]
Removed in https://github.com/valnet/valuenetwork/commit/f3569c83a1d07a2d7e501e89dda14f80d2fc02c3
