### ISSUE TITLE
Process context agent and event and commitment context agents can get out of sync

### ISSUE THREAD

**Issue by bhaugen** [valnet/valuenetwork#325]
If a process starts out in the wrong context, and then is changed, all of the appendages stay in the previous context, so they are out of sync.

The process takes place in the context of the context agent,, so they should all be in sync.

Possible solutions:

* Do not reproduce the context agent on the commitments and events and always take it from the process.
* If the process context agent changes, propagate the change to all the events and commitments.

**Comment by fosterlynn** [comment]
I would vote for the second option, propagate it down from the process.
Less confusion among programmers at least, and in admin too, where for
commitments and events without processes or exchanges, you need that
context agent.

Also, need to check Exchange and see if it propagates properly.

**Comment by fosterlynn** [comment]
Re-opening, still need to test script to fix existing data.

**Comment by fosterlynn** [comment]
Script to fix old data tested.  (Not run yet in production environments.)
