### ISSUE TITLE
Creating and editing work requirements UI improvements

### ISSUE THREAD

**Issue by TiberiusB** [valnet/valuenetwork#378]
1. When I create a type of work I have no choice to chose the Due Date. 
https://lh3.googleusercontent.com/YE300VEdVp9NOKZN8KiT4TJjLSUkAdPxbJ1acXqH9CY=w670-h532-no 
2. The due date is there on the Edit work requirement. 
https://lh3.googleusercontent.com/jGdkLr8ZoWV9z-lc5CpzoteGX57CSJvsyAlhXuvKvbw=w679-h534-no 

Moreover, I cannot change the "Type of work" when I edit a Work requirement. 

Perhaps a text somewhere saying that work requirements are aligned by Due Date. The less the user wonders how things are done, the lower the frustration, the higher the probability to use the system. 

Another thing, I would make Create and Change the work requirement popups look the same, both having Due Dates and both having the Type of work parameter to change.

**Comment by bhaugen** [comment]
![image](https://cloud.githubusercontent.com/assets/117439/7899158/39bcb88a-06de-11e5-87cd-b02033ed42f2.png)

**Comment by bhaugen** [comment]
When resolving this issue, don't forget that when somebody has committed to do the work, nobody else should be able to change the requirement.
