### ISSUE TITLE
My Contributions

### ISSUE THREAD

**Issue by TiberiusB** [valnet/valuenetwork#382]
I think it would be much more useful if we brake down contributions into Time, Financial, Meterial and others, on the My work / My contributions page. 

I find myself often enough looking through contributions to see is I logged a financial contribution, which is usually buried in the long list, dominated by Time contributions.

**Comment by bhaugen** [comment]
Do you think that would be better in sections? Or with filters? Or with separate lists for each type?

**Comment by bhaugen** [comment]
@TiberiusB - do you get email notifications of these issue-closing events?
