### ISSUE TITLE
Work Now page creates an event no matter what

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#411]
Even with no time on the start-stop and no time in the hours-minutes, an event was created.  I just went in to look at it....

(Maybe resolve if people still want this functionality before fixing, I know it is complicated code.)

**Comment by bhaugen** [comment]
Yup, that's what it does. And it is complicated code. Which is why I want
to kill it is nobody is using it.

**Comment by fosterlynn** [comment]
OK let's leave it
