### ISSUE TITLE
Need to split cash receipt into distributions

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#427]
Can get one check for multiple orders, etc.  Or for items that require different value equations.  So when run the distribution, need to be able to connect with the right cash distribution but distribute just part of it.

**Comment by bhaugen** [comment]
Questions and comments:
* Distributions allow selecting multiple cash receipts or multiple source distributions. What happens, for example, if somebody selects two cash receipts and enters a distribution amount that is different from the cash receipt amount, or the combined cash receipt amounts?
     * Subtract the amount from the first cash receipt, or if more than the first cash receipt amount, subtract the difference from the second one?
     * Don't allow entry of a distribution amount if they select more than one cash receipt or source distribution?
     * Or what?

The first option above requires validating their entry against the sum of the cash receipt or source distribution amounts, and the second option requires validating against one selection, which is somewhat easier in that it does not require a custom validation method.

Also, seems a bit cleaner to use a different form field for a partial cash receipt or source distribution amount than to use the existing "Amount to distribute" field.

**Comment by fosterlynn** [comment]
Good question.  Thoughts: It seems like a different scenario to take multiple cash receipts and to take a partial cash receipt, and I would vote for basically the second option.  Maybe this should be a separate option in the UI too.  The current one is multiple cash receipts, period, no partials.  The new one would be one cash receipt with an option (or a requirement, used only for partials?) to enter the partial amount too.  I also agree about not using the current field for that.
