### ISSUE TITLE
project status lists

### ISSUE THREAD

**Issue by bhaugen** [valnet/valuenetwork#441]
Loomio Comment by Frederic Durville:
What I would like to be able to see, but do not know yet exactly how to do it, is a simple list of all projects, with a very brief status, so one can see at once what activity is going on, what project is being currently worked on. And that list should be updated about once a week. Or may be it could be separated in 2 lists: one lists the projects that have seen some activity this week, and the other are the projects that have NOT seen any activity this week.

**Comment by bhaugen** [comment]
I revived an old page that might have be a starting point for content:
http://nrp.sensorica.co/accounting/today/

**Comment by fdurville** [comment]
It is interesting and it is a start. A couple of thoughts:
1). Instead (or may be in addition) of having a list of "planned" event or activity, would it possible to see the amount of work being logged for each project?
2). The list as it is has each and every single item registered under each project. Would it possible to just count the number of "items" and display this number?
3). Instead of being "today", can it be just at the end of the week (or the month)?
4). Is it also possible to add the list of all the other projects (those that have no registered activity for the period), or may be the total number of other projects?

I have started to sketch a brief outline https://docs.google.com/document/d/1TXfyZtieskqjGNtl2mzJOYRp3dSTuhEyIVs0SKmHI0w/edit

**Comment by bhaugen** [comment]
@fdurville - thank you very much! That is the perfect form of feedback.

I'll have (at least most of) this stuff done by Monday latest.

**Comment by bhaugen** [comment]
@fdurville (and anybody else who gets these issue notifications): for This Week, do you want a calendar week, or the last 7 days?

For example, today is Thursday. So this calendar week would start at the beginning of the week*. while the last 7 days would start last Thursday (or Friday, but whatever, I'd start last Thursday if that's what people want).

This calendar week could start on Sunday (as in Google Calendar) or Monday (as in the ISO calendar or most business work weeks). So if you want this calendar week, what day should it start on?

If I don't get any firm opinions, I'll go with the last 7 days.

**Comment by fdurville** [comment]
@bhaugen 
Yes, just the last 7 days is fine.

**Comment by bhaugen** [comment]
@fdurville - 
First draft deployed:
http://nrp.sensorica.co/accounting/this-week/

Not exactly like your outline, because each project is broken into many processes, and each task is inputs to a process.

Probably needs more refinement. Please suggest improvements.

And I don't have the financial income and contributions yet. Do you want those by $totals, or a list of individual contributions, or both? And should those be for the week, or total for the project?

**Comment by bhaugen** [comment]
Look for
johndanger Artistic 320.00 HR Aug. 30, 2015

Good job! I guess you can do that many hours per day on artistic work. We obviously chose the wrong professions...

**Comment by fdurville** [comment]
Whoa.. indeed... without even counting the additional time he also logged the same week! Yes, I am sure it is a mistake... I do not know about sending notification to teammates, would be more appropriate actually to first send a note to johndanger. And maybe there should be an automatic alert when time is logged, if the value exceeds a certain threshold, have a warning to confirm?

OK, so the top is great, I like that (obviously, that is what I had suggested).

The list of "activities" is way too long. I am not sure exactly how to cut it down.

One question: is it possible to show only the tasks that have seen activity that week, and then only show the total time contribution (from all participants)? (see the google doc https://docs.google.com/document/d/1TXfyZtieskqjGNtl2mzJOYRp3dSTuhEyIVs0SKmHI0w/edit


And for financial contributions, for the moment, let's not do that.

**Comment by bhaugen** [comment]
> One question: is it possible to show only the tasks that have seen activity that week,
> and then only show the total time contribution (from all participants)?

Sure. We can condense, summarize, whatever, to any amount of detail that is useful.

Part of the problem here is that Sensorica's data is messy. People don't mark anything finished, and a lot of it is.

**Comment by bhaugen** [comment]
Proposal: in my next coding round (next draft of the report), how about if I show only the tasks that have activity, and show each of the participants but summarize their hours?

So for each task with any activity, it would show only one line for each of the participants with the total number of hours worked?

This is normal, by the way. I just start these things with a fairly rough draft, and then beat it into shape. Hope that's not too tedious for you.

By the way, Lynn thought a financial contributions report would be interesting, but maybe it should be a different report.

**Comment by fdurville** [comment]
You do have a good point that sensorica data is messy!

I like your proposal, that sounds great. And I am perfectly fine with whichever way works for you. I do not find it tedious, normal trading back and forth.

For the financial contributions, yes I also thought it would be interesting, but I would agree with Lynn at this point, it probably should be a different report.

**Comment by bhaugen** [comment]
Working the proposal above. Taking longer than I expected, which is not unusual, and then we got a bunch of other stuff on the table. I assume you don't care about timing that much, but you might have expected I would have something new to show today, and so did I, so this is just to reset both of our expectations.

It's coming along. I am resetting my expectations toward Wednesday.

**Comment by fdurville** [comment]
You are right that I do not care about timing. Just the fact that you are working on this is already very significant for me. So any time will be good!

**Comment by bhaugen** [comment]
next draft up, same location

probably needs more work, but I think I fixed the bug that was plaguing me this morning.

**Comment by fdurville** [comment]
I like it!! Thank you so much Bob for doing this. 
One can now see on one page what is going on... to me, that is very useful.

**Comment by bhaugen** [comment]
Thank you. I think it will be useful for all of us who are not in Montreal or part of the daily action. And as Lynn says, might also be useful for spotting mistakes, like that 320 hours probably was.

**Comment by bhaugen** [comment]
Closed for now. Might want more work later.
