### ISSUE TITLE
Purchase logging - UI - quick to fix

### ISSUE THREAD

**Issue by TiberiusB** [valnet/valuenetwork#469]
In the Purchase log form we can eliminate one step, by having the Expense directly calculated from the sum of Payments. See Screenshot from link below. 
https://drive.google.com/file/d/0BzrQyEif2HItbG5zOWhkM09PMDQ/view 

Extracted from this logging page. 
http://valnet.webfactional.com/accounting/exchange/520/

**Comment by fosterlynn** [comment]
Thanks for screen shots!

I guess it all depends on what order you enter stuff.  (That help is not quite right: the value of the items received plus the expenses should equal the payment(s).  We should make it more general, as this is a page for all exchanges.)  But in fact things might not balance either, say you haven't paid for it all yet.  And there is other information about each (receipts, expenses, payments) that needs to be entered.

So, I'm not sure I understand how your suggestion would actually work, need more detail with examples of different order of entry.  But am all for making things more automatic whenever possible.  Also this is undergoing a complete re-write as we speak, so any improvements in features would be good to put into that.

**Comment by TiberiusB** [comment]
I think Expenses is confusing there. I was under the impression that the Expense is the total, and Payment can be split for more than one member. In any case, this is the use case I was operating under. 
Yes, when there's a list of items received the whole thing becomes more complicated. That is another use case. 
So, to make it clear, what does Expense means in my use case (a few individuals sharing Payment for one thing)? 

Another thing that we don't understand (Myself and Josh) is the items in the "Types of expense" list, in the context of a Purchase contribution. See this picture https://drive.google.com/file/d/0BzrQyEif2HItMTF1Wk5hSm5Bb2M/view 
This list only presents expense items that should appear in the Expense logging context ? 

I am confused... This should be communicated to the UI / UX team.

**Comment by TiberiusB** [comment]
I think this tutorial requires more explanations. 
https://speakerdeck.com/player/178be326c45b42bcb9e74b80cb748d88# 
I went through it again, and I don't see clarifications to my questions. 
Also, if the help on the Purchase page is not accurate, we need to improve it. 

Is it possible that "Expense" has different meanings when used in the context of "Expense logging" and "Purchase logging"? If so, even is the meaning is only slightly different, I would use two different terms instead of just one.

**Comment by fosterlynn** [comment]
I see there is some confusion, sorry.  So on a Purchase, you have Receipts (actual items you got to use or consume, etc), Expenses (other things you spent secondarily like gas to pick up your items or shipping or tax), and Payments.  Those are event types.  The payments should eventually equal the receipts value plus the expenses, usually.

There is another use case called Expense (thus confusing).  That is for rent and other things that don't involve Receipts.  So the event types there are Expense and Payment, which should eventually equal usually.  I suppose Expense and Purchase use cases could have been combined.

Again, this is being totally re-written now, and you will be able to define all types of exchanges and what makes them up.  Completely user definable at both levels.  I'd suggest we don't waste time doing enhancements to the current system or the tutorials until the new code is complete.

I'd be happy to go through it with other people if that will help in the meantime.

**Comment by fosterlynn** [comment]
Tibi, that is the point of the totals at the top, where you can see the balance of incoming value and outgoing value.  All of the detail is real life events, and should always match what has actually occurred.  This is always the case in all process and exchange logging, which are all formatted similarly.

If you have been recording expenses that are derived totals and are not what you have actually expensed as part of the exchange, then yes it will need to be fixed.  I don't know of a quick way, as only some will be wrong.

Do you want to re-write the help text you created for this page, or should we do so?

Do you think we need changes to the Expense detail help (in screen shot below)?

![expense-screen](https://cloud.githubusercontent.com/assets/3776081/12647127/40ac1efe-c599-11e5-99ed-c4355908c7f5.png)

**Comment by fosterlynn** [comment]
Closing, this is superceded by the new exchange type feature.
