### ISSUE TITLE
Defaults in the UI - UI UX

### ISSUE THREAD

**Issue by TiberiusB** [valnet/valuenetwork#470]
When someone is logged into the system the system should always default to that individual's name whenever the individual needs to chose an agent from a list to log time, a purchase, etc... 
In the majority of cases affiliates log their own stuff.

**Comment by fosterlynn** [comment]
Yes.  When it doesn't default, that is a bug.  Do you remember where?

**Comment by fosterlynn** [comment]
I checked and couldn't find where it did not default.  I checked logging work in processes and exchanges, and logging payments in exchanges.  Anywhere else it should default?

**Comment by fosterlynn** [comment]
Closing until we have a verifyable report.
